#pragma once

#include "melkor/limits.hpp"
#include "melkor/scene.hpp"

#include <cstddef>
#include <cstdint>
#include <optional>
#include <ostream>
#include <string>
#include <vector>

namespace melkor {

// PLY format options
enum class PlyFormat {
    Binary,  // Binary little-endian (recommended for speed)
    Ascii    // ASCII (human readable, larger files)
};

// Configuration for PLY writing
struct PlyWriteConfig {
    PlyFormat format = PlyFormat::Binary;

    // Include spherical harmonics beyond DC (degree 0)
    bool include_sh_rest = false;

    // Comment to include in header
    std::string comment = "Generated by melkor";
};

// Result of PLY writing
struct PlyWriteResult {
    bool success = false;
    std::string error_message;
    size_t bytes_written = 0;
    // Successful writes may still need to report a representational adjustment. In particular,
    // the training-domain PLY profile cannot encode canonical opacity endpoints as finite logits,
    // so 0 and 1 are clamped explicitly and reported here rather than hidden in the math oracle.
    std::vector<Diagnostic> diagnostics;
};

// PLY file writer for Gaussian splatting format
class PlyWriter {
public:
    PlyWriter();
    ~PlyWriter();

    // Write to file
    PlyWriteResult writeToFile(const std::string& filepath, const SplatData& data,
                               const PlyWriteConfig& config = {});

    // Write to stream
    PlyWriteResult writeToStream(std::ostream& stream, const SplatData& data,
                                 const PlyWriteConfig& config = {});

    // Write to memory buffer
    PlyWriteResult writeToBuffer(std::vector<uint8_t>& buffer, const SplatData& data,
                                 const PlyWriteConfig& config = {});
};

// PLY file reader for Gaussian splatting format
class PlyReader {
public:
    PlyReader();
    ~PlyReader();

    struct Metadata {
        enum class Encoding {
            Unknown,
            Ascii,
            BinaryLittleEndian,
            BinaryBigEndian,
        };

        Encoding encoding = Encoding::Unknown;
        size_t declared_vertices = 0;
        bool has_position = false;
        bool has_sh_dc = false;
        bool has_rgb = false;
        bool has_opacity = false;
        bool has_scale = false;
        bool has_rotation = false;
        bool has_sh_rest = false;
    };

    struct ReadResult {
        bool success = false;
        std::string error_message;
        // Engaged on every successful read, including an empty PLY. Optional keeps the invalid
        // default state out of SplatData while preserving the reader's structured metadata.
        std::optional<SplatData> data;
        Metadata metadata;
    };

    // Read from file. `limits` bounds resource use: the file bytes, the declared vertex count, and
    // the reconstructed canonical arrays are charged against a Budget before allocation, so a
    // well-formed header declaring an enormous count is refused by policy, not only by bad_alloc.
    ReadResult readFromFile(const std::string& filepath,
                            const Limits& limits = Limits::for_profile(LimitsProfile::desktop));

    // Read from memory buffer (see readFromFile for the meaning of `limits`).
    ReadResult readFromBuffer(const uint8_t* data, size_t size,
                              const Limits& limits = Limits::for_profile(LimitsProfile::desktop));
};

}  // namespace melkor
