#pragma once

#include "melkor/gaussian_data.hpp"
#include "melkor/limits.hpp"
#include <string>
#include <ostream>

namespace melkor {

// PLY format options
enum class PlyFormat {
    Binary,      // Binary little-endian (recommended for speed)
    Ascii        // ASCII (human readable, larger files)
};

// Configuration for PLY writing
struct PlyWriteConfig {
    PlyFormat format = PlyFormat::Binary;
    
    // Include spherical harmonics beyond DC (degree 0)
    bool include_sh_rest = false;
    
    // Comment to include in header
    std::string comment = "Generated by melkor";
};

// Result of PLY writing
struct PlyWriteResult {
    bool success = false;
    std::string error_message;
    size_t bytes_written = 0;
};

// PLY file writer for Gaussian splatting format
class PlyWriter {
public:
    PlyWriter();
    ~PlyWriter();
    
    // Write to file
    PlyWriteResult writeToFile(const std::string& filepath,
                               const GaussianCloud& cloud,
                               const PlyWriteConfig& config = {});
    
    // Write to stream
    PlyWriteResult writeToStream(std::ostream& stream,
                                 const GaussianCloud& cloud,
                                 const PlyWriteConfig& config = {});
    
    // Write to memory buffer
    PlyWriteResult writeToBuffer(std::vector<uint8_t>& buffer,
                                 const GaussianCloud& cloud,
                                 const PlyWriteConfig& config = {});
};

// PLY file reader for Gaussian splatting format
class PlyReader {
public:
    PlyReader();
    ~PlyReader();

    struct Metadata {
        enum class Encoding {
            Unknown,
            Ascii,
            BinaryLittleEndian,
            BinaryBigEndian,
        };

        Encoding encoding = Encoding::Unknown;
        size_t declared_vertices = 0;
        bool has_position = false;
        bool has_sh_dc = false;
        bool has_rgb = false;
        bool has_opacity = false;
        bool has_scale = false;
        bool has_rotation = false;
        bool has_sh_rest = false;
    };
    
    struct ReadResult {
        bool success = false;
        std::string error_message;
        GaussianCloud cloud;
        Metadata metadata;
    };
    
    // Read from file. `limits` bounds resource use: the file bytes, the declared vertex count, and
    // the reconstructed cloud are charged against a Budget before they are allocated, so a
    // well-formed header declaring an enormous count is refused by policy, not only by bad_alloc.
    ReadResult readFromFile(const std::string& filepath,
                            const Limits& limits = Limits::for_profile(LimitsProfile::desktop));

    // Read from memory buffer (see readFromFile for the meaning of `limits`).
    ReadResult readFromBuffer(const uint8_t* data, size_t size,
                              const Limits& limits = Limits::for_profile(LimitsProfile::desktop));
};

} // namespace melkor
