function showBootstrapError(message, error) {
  const overlay = document.getElementById("overlay");
  const title = document.getElementById("ov-title");
  const retry = document.getElementById("ov-retry");
  for (const id of ["app", "canvas-description", "hud", "scenes", "bar", "tl", "dropTarget", "helpDialog"]) {
    document.getElementById(id).inert = true;
  }
  document.getElementById("app").setAttribute("aria-busy", "false");
  title.textContent = message;
  title.className = "title err";
  overlay.classList.add("show", "error");
  overlay.setAttribute("role", "alertdialog");
  overlay.setAttribute("aria-live", "assertive");
  overlay.setAttribute("aria-modal", "true");
  retry.hidden = false;
  retry.textContent = "Reload";
  retry.addEventListener("click", () => location.reload(), { once: true });
  window.__viewer = {
    state: { ready: true, loading: false, rendered: false, error: message },
    getStats() { return { ...this.state }; },
  };
  queueMicrotask(() => retry.focus({ preventScroll: true }));
  console.error(message, error);
}

let THREE;
let SparkRenderer;
let SplatFileType;
let SplatMesh;
let SparkControls;
let validateLocalFile;
let cancelLocalFileValidation;
try {
  let prepareLocalFileValidation;
  ({ cancelLocalFileValidation, prepareLocalFileValidation, validateLocalFile } =
    await import("./local-file-validator.js"));
  await prepareLocalFileValidation();
  THREE = await import("three");
  ({ SparkRenderer, SplatFileType, SplatMesh, SparkControls } = await import("@sparkjsdev/spark"));
} catch (error) {
  showBootstrapError("The viewer runtime could not start. Reload the viewer or restore its runtime files.", error);
  await new Promise(() => {});
}

// ---------------------------------------------------------------------------
// Scene catalog: city / area gaussian splats downloaded into public/splats/
// ---------------------------------------------------------------------------
const SCENES = [
  { id: "snow-street",   label: "Snowy Street",   file: "snow-street.spz",   fmt: "SPZ",  note: "urban street · ~982K" },
  { id: "valley",        label: "Valley",         file: "valley.spz",        fmt: "SPZ",  note: "landscape · 500K" },
  { id: "sutro",         label: "Sutro Tower (SF)",file: "sutro.zip",        fmt: "SOG",  note: "cityscape · ~2.0M" },
  { id: "wave-static",   label: "Wave Field",     file: "generated/wave.splat", fmt: "SPLAT", note: "project-owned demo · 4K" },
  { id: "distant-igloo", label: "Distant Igloo",  file: "distant-igloo.spz", fmt: "SPZ",  note: "outdoor area · 347K" },
  { id: "igloo-ply",     label: "Igloo · PLY (melkor)", file: "distant-igloo.ply", fmt: "PLY", note: "melkor SPZ→PLY · 347K" },
  // 4D temporal sequence (per-frame PLYs + manifest.json, the shape a 4D-GS
  // export produces). `optional`: generated by `node make-4d-demo.js`.
  { id: "wave-4d",       label: "Wave · 4D",      manifest: "4d/wave/manifest.json", fmt: "4D-PLY", temporal: true, optional: true, note: "temporal sequence · 24 frames" },
  // Same sequence packed to per-frame SPZ by pack-4d.js (~94% smaller) — the
  // "4D format producer" output; the temporal player streams it identically.
  { id: "wave-4d-spz",   label: "Wave · 4D (SPZ)", manifest: "4d/wave-spz/manifest.json", fmt: "4D-SPZ", temporal: true, optional: true, note: "SPZ-compressed · 24 frames" },
];
const SPLAT_DIR = "./public/splats/";
const LOCAL_FILE_TYPES = new Map([
  ["ply",    { fmt: "PLY",    type: SplatFileType.PLY }],
  ["spz",    { fmt: "SPZ",    type: SplatFileType.SPZ }],
  ["splat",  { fmt: "SPLAT",  type: SplatFileType.SPLAT }],
  ["ksplat", { fmt: "KSPLAT", type: SplatFileType.KSPLAT }],
  ["sog",    { fmt: "SOG",    type: SplatFileType.PCSOGSZIP }],
  ["zip",    { fmt: "SOG",    type: SplatFileType.PCSOGSZIP }],
]);

const countFormatter = new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 });
function formatCount(value) {
  return Number.isFinite(value) && value >= 0 ? countFormatter.format(value) : "—";
}
function formatBytes(bytes) {
  if (!Number.isFinite(bytes) || bytes < 0) return "—";
  if (bytes === 0) return "0 B";
  const units = ["B", "KiB", "MiB", "GiB"];
  const index = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1);
  const value = bytes / (1024 ** index);
  const digits = value >= 100 || index === 0 ? 0 : value >= 10 ? 1 : 2;
  return `${new Intl.NumberFormat("en-US", { maximumFractionDigits: digits }).format(value)} ${units[index]}`;
}
// ---------------------------------------------------------------------------
// Three.js + Spark setup
// ---------------------------------------------------------------------------
const appEl = document.getElementById("app");
const reducedMotion = window.matchMedia("(prefers-reduced-motion: reduce)");
const scene = new THREE.Scene();
scene.background = new THREE.Color(0x0b0c10);

const camera = new THREE.PerspectiveCamera(
  60,
  Math.max(window.innerWidth, 1) / Math.max(window.innerHeight, 1),
  0.05,
  2000,
);
camera.position.set(0, 0, 5);

let renderer;
let spark;
let controls;
let renderAvailable = true;
try {
  renderer = new THREE.WebGLRenderer({
    antialias: false,
    // Test screenshots/readPixels need a retained buffer. Production does not.
    preserveDrawingBuffer: navigator.webdriver === true,
  });
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  renderer.setSize(Math.max(window.innerWidth, 1), Math.max(window.innerHeight, 1));
  renderer.domElement.tabIndex = 0;
  renderer.domElement.setAttribute("role", "application");
  renderer.domElement.setAttribute("aria-label", "Interactive Gaussian splat viewport");
  renderer.domElement.setAttribute("aria-describedby", "canvas-description");
  renderer.domElement.textContent = "Interactive Gaussian splat viewport. Use the camera controls to select a view.";
  appEl.appendChild(renderer.domElement);

  spark = new SparkRenderer({ renderer });
  scene.add(spark);
  controls = new SparkControls({ canvas: renderer.domElement });
} catch (error) {
  try { renderer?.dispose(); } catch {}
  showBootstrapError("WebGL 2 could not start. Enable graphics acceleration or use a supported device.", error);
  await new Promise(() => {});
}

// Camera rig: we orbit / frame around `target`.
const target = new THREE.Vector3(0, 0, 0);
let orbitRadius = 5;
let orbitEnabled = !reducedMotion.matches;
let orbitAzimuth = Math.PI * 0.25;   // radians
let orbitElevation = Math.PI * 0.09; // radians (~16deg, low 3/4 aerial)
const ORBIT_SPEED = 0.18;            // rad/sec
let manualControl = false;           // user grabbed the camera via SparkControls
let activeCameraView = null;

let currentMesh = null;
let currentScene = null;
let progressiveMesh = null;
let localSceneDef = null;             // one retained File handle; replaced on the next import
let pendingLocalSceneDef = null;      // candidate retained only while its load is in flight
let frameCountSinceLoad = 0;
let loadGen = 0;                     // monotonic token: only the latest load mutates state
let localOpenGen = 0;                // only the latest file or scene choice can start a local load

function detachProgressiveMesh() {
  if (!progressiveMesh) return;
  scene.remove(progressiveMesh);
  progressiveMesh = null;
}

// ---------------------------------------------------------------------------
// Framing: position camera so the splat bounding sphere fills the view
// ---------------------------------------------------------------------------
// Packed scenes can have invalid Spark bounds. Use bounded center samples instead.
// Keep the more opaque half. Then use median coordinates and a percentile radius.
function computeBounds(mesh) {
  const maxSamples = 100_000;
  const knownCount = splatCountOf(mesh);
  const declaredCount = Number.isSafeInteger(knownCount) && knownCount > 0 ? knownCount : 0;
  const capacity = Math.min(declaredCount || maxSamples, maxSamples);
  const xs = new Float64Array(capacity);
  const ys = new Float64Array(capacity);
  const zs = new Float64Array(capacity);
  const opacities = new Float64Array(capacity);
  let sampleCount = 0;

  const addSample = (c, opacity) => {
    if (!Number.isFinite(c.x) || !Number.isFinite(c.y) || !Number.isFinite(c.z)) return;
    if (sampleCount >= capacity) return;
    xs[sampleCount] = c.x;
    ys[sampleCount] = c.y;
    zs[sampleCount] = c.z;
    opacities[sampleCount] = Number.isFinite(opacity) ? opacity : 1;
    sampleCount++;
  };

  // PackedSplats exposes indexed reads. Sample its full index range without
  // decoding every splat on the UI thread.
  if (declaredCount > 0 && typeof mesh?.splats?.getSplat === "function") {
    for (let sample = 0; sample < capacity; sample++) {
      const index = capacity === 1
        ? 0
        : Math.floor(sample * (declaredCount - 1) / (capacity - 1));
      const splat = mesh.splats.getSplat(index);
      addSample(splat.center, splat.opacity);
    }
  } else {
    // Keep the fallback bounded for alternate Spark splat sources.
    const stop = {};
    let visited = 0;
    try {
      mesh.forEachSplat((_i, c, _s, _q, opacity) => {
        if (visited++ >= capacity) throw stop;
        addSample(c, opacity);
      });
    } catch (error) {
      if (error !== stop) throw error;
    }
  }
  if (sampleCount === 0) return null;

  const scratch = new Float64Array(sampleCount);
  scratch.set(opacities.subarray(0, sampleCount));
  scratch.sort();
  const opacityThreshold = scratch[sampleCount >> 1];
  let solidCount = 0;
  for (let index = 0; index < sampleCount; index++) {
    if (opacities[index] >= opacityThreshold) solidCount++;
  }
  const useAll = solidCount < 64;
  if (useAll) solidCount = sampleCount;

  const median = (values) => {
    let output = 0;
    for (let index = 0; index < sampleCount; index++) {
      if (useAll || opacities[index] >= opacityThreshold) scratch[output++] = values[index];
    }
    scratch.subarray(0, output).sort();
    return scratch[output >> 1];
  };
  const center = new THREE.Vector3(median(xs), median(ys), median(zs));
  let output = 0;
  for (let index = 0; index < sampleCount; index++) {
    if (!useAll && opacities[index] < opacityThreshold) continue;
    scratch[output++] = Math.hypot(
      xs[index] - center.x,
      ys[index] - center.y,
      zs[index] - center.z,
    );
  }
  scratch.subarray(0, output).sort();
  const radiusIndex = Math.min(output - 1, Math.floor(output * 0.9));
  const radius = scratch[radiusIndex];
  if (!Number.isFinite(radius)) return null;
  return {
    center,
    radius: Math.max(radius, 1e-3),
    count: declaredCount || sampleCount,
    solid: solidCount,
  };
}

function frameMesh(mesh) {
  let b = null;
  try {
    b = computeBounds(mesh);
  } catch (error) {
    console.warn("Could not compute scene bounds. The viewer will use the default camera.", error);
  }
  if (!b) { target.set(0, 0, 0); orbitRadius = 5; applyOrbit(); return; }
  // Bounds are in mesh-local space; apply the mesh world transform to the center.
  const center = b.center.clone().multiply(mesh.scale).applyQuaternion(mesh.quaternion).add(mesh.position);
  target.copy(center);
  const s = Math.max(mesh.scale.x, mesh.scale.y, mesh.scale.z);
  const r = Math.max(b.radius * s, 1e-3);
  const fov = THREE.MathUtils.degToRad(camera.fov);
  orbitRadius = (r / Math.sin(fov / 2)) * 1.35;
  camera.near = Math.max(orbitRadius / 1000, 0.01);
  camera.far = orbitRadius * 50;
  camera.updateProjectionMatrix();
  applyOrbit();
}

function applyOrbit() {
  const ce = Math.cos(orbitElevation), se = Math.sin(orbitElevation);
  const ca = Math.cos(orbitAzimuth), sa = Math.sin(orbitAzimuth);
  camera.position.set(
    target.x + orbitRadius * ce * ca,
    target.y + orbitRadius * se,
    target.z + orbitRadius * ce * sa,
  );
  camera.lookAt(target);
}

// Named viewpoints ("camera feeds") used by the UI + tests.
const VIEWS = {
  front: [Math.PI * 0.5,  Math.PI * 0.06],
  side:  [0.0,            Math.PI * 0.06],
  top:   [Math.PI * 0.5,  Math.PI * 0.48],
  iso:   [Math.PI * 0.22, Math.PI * 0.10],
};
function setView(name) {
  const v = VIEWS[name];
  if (!v) return;
  orbitEnabled = false; manualControl = false; syncOrbitBtn();
  activeCameraView = name; syncCameraButtons();
  orbitAzimuth = v[0]; orbitElevation = v[1];
  applyOrbit();
}

// ---------------------------------------------------------------------------
// Scene loading
// ---------------------------------------------------------------------------
const overlay = document.getElementById("overlay");
const overlayCard = overlay.querySelector(".card");
const ovTitle = document.getElementById("ov-title");
const track = document.getElementById("track");
const pct = document.getElementById("pct");
const ovRetry = document.getElementById("ov-retry");
const ovDismiss = document.getElementById("ov-dismiss");
const helpDialog = document.getElementById("helpDialog");
const modalBackground = ["app", "canvas-description", "hud", "scenes", "bar", "tl", "dropTarget", "helpDialog"]
  .map((id) => document.getElementById(id));
let overlayRetry = null;
let overlayDismiss = null;
let overlayReturnFocus = null;
let errorDialogOpen = false;
let overlayGeneration = 0;
let overlayErrorKind = null;

function setModalBackgroundInert(inert) {
  for (const element of modalBackground) element.inert = inert;
}
function closeErrorDialog(restoreFocus) {
  if (!errorDialogOpen) return;
  errorDialogOpen = false;
  setModalBackgroundInert(false);
  overlay.removeAttribute("aria-modal");
  const returnFocus = overlayReturnFocus;
  overlayReturnFocus = null;
  if (restoreFocus && returnFocus?.isConnected) {
    requestAnimationFrame(() => returnFocus.focus({ preventScroll: true }));
  }
}

function clearOverlayActions() {
  overlayRetry = null;
  overlayDismiss = null;
  ovRetry.hidden = true;
  ovRetry.textContent = "Retry";
  ovDismiss.hidden = true;
  ovDismiss.textContent = "Dismiss";
}
function showOverlay(title) {
  const generation = ++overlayGeneration;
  closeErrorDialog(true);
  clearOverlayActions();
  overlayErrorKind = null;
  overlay.setAttribute("role", "status");
  overlay.setAttribute("aria-live", "polite");
  appEl.setAttribute("aria-busy", "true");
  ovTitle.textContent = title; ovTitle.className = "title";
  track.value = 0; pct.textContent = "0%";
  track.setAttribute("aria-valuenow", "0");
  track.setAttribute("aria-valuetext", "0 percent");
  overlay.classList.remove("error"); overlay.classList.add("show");
  return generation;
}
function showError(
  msg,
  retry = null,
  retryLabel = "Retry",
  dismiss = null,
  kind = "generic",
  dismissLabel = "Dismiss",
) {
  ++overlayGeneration;
  if (helpDialog.open) helpDialog.close();
  if (!errorDialogOpen) {
    const activeElement = document.activeElement;
    overlayReturnFocus = activeElement instanceof HTMLElement && !overlay.contains(activeElement)
      ? activeElement
      : renderer.domElement;
  }
  clearOverlayActions();
  overlayErrorKind = kind;
  errorDialogOpen = true;
  setModalBackgroundInert(true);
  overlay.setAttribute("role", "alertdialog");
  overlay.setAttribute("aria-live", "assertive");
  overlay.setAttribute("aria-modal", "true");
  appEl.setAttribute("aria-busy", "false");
  ovTitle.textContent = msg; ovTitle.className = "title err";
  overlay.classList.remove("streaming"); overlay.classList.add("show", "error");
  overlayRetry = typeof retry === "function" ? retry : null;
  overlayDismiss = typeof dismiss === "function" ? dismiss : null;
  ovRetry.hidden = !overlayRetry;
  ovRetry.textContent = retryLabel;
  ovDismiss.hidden = !overlayDismiss;
  ovDismiss.textContent = dismissLabel;
  queueMicrotask(() => (overlayRetry ? ovRetry : overlayDismiss ? ovDismiss : overlayCard)
    .focus({ preventScroll: true }));
}
function hideOverlay(expectedGeneration = null) {
  if (expectedGeneration !== null && expectedGeneration !== overlayGeneration) return false;
  ++overlayGeneration;
  clearOverlayActions();
  overlayErrorKind = null;
  appEl.setAttribute("aria-busy", "false");
  overlay.classList.remove("show", "streaming", "error");
  closeErrorDialog(true);
  return true;
}
ovRetry.addEventListener("click", () => {
  const retry = overlayRetry;
  retry?.();
});
function dismissOverlayError() {
  if (!overlayDismiss) return;
  const dismiss = overlayDismiss;
  hideOverlay();
  dismiss();
}
ovDismiss.addEventListener("click", dismissOverlayError);
overlay.addEventListener("keydown", (event) => {
  if (!errorDialogOpen) return;
  if (event.key === "Escape") {
    if (!overlayDismiss) return;
    event.preventDefault();
    event.stopPropagation();
    dismissOverlayError();
    return;
  }
  if (event.key !== "Tab") return;
  const focusable = [ovRetry, ovDismiss].filter((button) => !button.hidden);
  if (focusable.length === 0) {
    event.preventDefault();
    overlayCard.focus();
    return;
  }
  const currentIndex = focusable.indexOf(document.activeElement);
  const nextIndex = event.shiftKey
    ? (currentIndex <= 0 ? focusable.length - 1 : currentIndex - 1)
    : (currentIndex < 0 || currentIndex === focusable.length - 1 ? 0 : currentIndex + 1);
  event.preventDefault();
  focusable[nextIndex].focus();
});

function updateLoadProgress(event) {
  if (event && event.lengthComputable && event.total) {
    const progress = Math.min(100, (event.loaded / event.total) * 100);
    const rounded = progress.toFixed(0);
    track.value = progress;
    pct.textContent = rounded + "%";
    track.setAttribute("aria-valuenow", progress.toFixed(1));
    track.setAttribute("aria-valuetext", rounded + " percent");
  } else if (event && event.loaded) {
    const loaded = formatBytes(event.loaded);
    pct.textContent = loaded;
    track.removeAttribute("aria-valuenow");
    track.setAttribute("aria-valuetext", loaded + " loaded");
  }
}

function splatCountOf(mesh) {
  try {
    return mesh?.splats?.getNumSplats?.()
        ?? mesh?.packedSplats?.numSplats
        ?? mesh?.context?.numSplats?.value
        ?? 0;
  } catch { return 0; }
}

function syncSceneURL(definition) {
  const url = new URL(window.location.href);
  if (definition.localFile) url.searchParams.delete("scene");
  else url.searchParams.set("scene", definition.id);
  window.history.replaceState(null, "", url);
}

async function loadScene(id, candidateDefinition = null) {
  if (!renderAvailable) return null;
  const def = candidateDefinition
    ?? (localSceneDef?.id === id ? localSceneDef : SCENES.find((s) => s.id === id));
  if (!def) throw new Error("unknown scene: " + id);
  if (!candidateDefinition) {
    ++localOpenGen;
    cancelLocalFileValidation();
  }
  if (!candidateDefinition) pendingLocalSceneDef = null;
  if (def.temporal) return load4DSequence(def);   // 4D sequence path
  const gen = ++loadGen;             // supersede any in-flight load (e.g. the boot auto-load)
  detachProgressiveMesh();
  state.loading = true; state.error = null; state.rendered = false;
  frameCountSinceLoad = 0;
  const overlayTicket = showOverlay(`${def.localFile ? "Opening" : "Loading"} ${def.label}…`);

  let mesh = null;
  let progressive = false;
  try {
    mesh = new SplatMesh({
      ...(def.localFile ? {
        stream: def.localFile.stream(),
        streamLength: def.localFile.size,
        fileName: def.localFile.name,
        fileType: def.fileType,
      } : {
        url: SPLAT_DIR + def.file,
      }),
      onProgress: (e) => {
        if (gen !== loadGen) return;
        updateLoadProgress(e);
      },
    });
    // These scenes use a Y-down, Z-forward frame. Rotate them into the three.js frame.
    mesh.quaternion.set(1, 0, 0, 0);

    // Add the first mesh early so Spark can show progressive load results.
    // Keep the active mesh visible during later loads.
    progressive = !currentMesh;
    state.progressive = progressive;
    if (progressive) {
      progressiveMesh = mesh;
      scene.add(mesh);
      overlay.classList.add("streaming");
    }
    await mesh.initialized;
  } catch (err) {
    if (progressive && mesh) { try { scene.remove(mesh); } catch {} }
    if (progressiveMesh === mesh) progressiveMesh = null;
    try { mesh?.dispose(); } catch {}
    if (gen !== loadGen) return null;
    state.loading = false; state.error = String(err);
    console.error("Failed to open " + def.label + ":", err);
    const canDismiss = Boolean(currentMesh && currentScene);
    const localCandidateFailed = Boolean(def.localFile && pendingLocalSceneDef === def);
    if (localCandidateFailed) pendingLocalSceneDef = null;
    showError("Could not open " + def.label + ". The file may be damaged or use an unsupported layout.",
      localCandidateFailed
        ? () => openLocalFilePickerFromError()
        : () => loadScene(def.id).catch(console.error),
      localCandidateFailed ? "Choose another file" : "Retry", canDismiss ? () => {
        // The active scene was never replaced. Clear only the candidate-load
        // error so automation and subsequent interactions see the recovered
        // current scene as healthy.
        state.error = null;
        state.inputError = null;
      } : null);
    throw err;
  }

  // A newer load started while this one was downloading: discard it silently.
  if (gen !== loadGen) {
    if (progressive) { try { scene.remove(mesh); } catch {} }
    if (progressiveMesh === mesh) progressiveMesh = null;
    try { mesh.dispose(); } catch {}
    return null;
  }

  // Swap the freshly-loaded mesh in for the previous one (no blank gap
  // mid-load). When progressive, the mesh is already in the scene.
  // A 4D cache is cleared only after replacement initialization succeeds;
  // damaged candidate files therefore cannot destroy the active sequence.
  if (seq4d) clear4d();
  if (currentMesh) { scene.remove(currentMesh); try { currentMesh.dispose(); } catch {} }
  currentMesh = mesh; currentScene = def;
  if (progressiveMesh === mesh) progressiveMesh = null;
  if (!progressive) scene.add(mesh);
  frameCountSinceLoad = 0;           // count frames rendered AFTER the swap, not during download
  frameMesh(mesh);
  orbitEnabled = !reducedMotion.matches; manualControl = false; activeCameraView = null;
  syncOrbitBtn(); syncCameraButtons();

  state.loading = false;
  state.scene = def.id;
  state.format = def.fmt;
  state.splatCount = splatCountOf(mesh);
  state.source = def.localFile ? "local" : "bundled";
  state.fileBytes = def.localFile?.size ?? null;
  state.inputError = null;
  if (def.localFile && pendingLocalSceneDef === def) {
    // Commit the catalog entry and retained File only after the candidate mesh
    // has initialized. A damaged replacement can never evict the last good
    // local file or leave the UI describing a mesh that is not displayed.
    localSceneDef = def;
    pendingLocalSceneDef = null;
    buildSceneButtons();
  }
  updateHud();
  updateSceneButtons();
  syncSceneURL(def);
  if (!hideOverlay(overlayTicket)) makeLocalErrorDismissible();
  return mesh;
}

// ---------------------------------------------------------------------------
// 4D temporal player — buffered-window streaming
// ---------------------------------------------------------------------------
// A 4D scene contains one PLY or SPZ file for each frame. A manifest.json file
// supplies { fps, frames: [...] }. The 4D-GS `export_perframe_3DGS.py` command
// produces this shape. The pinned SparkJS runtime does not play this sequence.
// This player keeps a bounded frame window around the playhead. It prefetches
// future frames and removes frames outside the window. One loaded frame is
// visible. Memory use is O(window), not O(sequence length).
const BUF_AHEAD = 6, BUF_BEHIND = 2, EVICT_MARGIN = 2;
const MAX_FRAME_RETRIES = 3, FRAME_RETRY_BASE_MS = 250;
const MAX_INFLIGHT_4D_FRAMES = 4;
const MAX_4D_FRAMES = 10_000;
const MAX_4D_MANIFEST_BYTES = 1024 * 1024;
const tl = document.getElementById("tl");
const tlPlay = document.getElementById("tlPlay");
const tlSlider = document.getElementById("tlSlider");
const tlLabel = document.getElementById("tlLabel");
const tlStatus = document.getElementById("tlStatus");
let seq4d = null;             // { base, frames:[...], count }
let cache4d = new Map();      // index -> ready SplatMesh (in scene, visible=false except active)
let loading4d = new Map();    // index -> in-flight Promise<mesh|null> (shared by concurrent callers)
let failed4d = new Map();     // index -> bounded retry state; prevents request storms on missing frames
let active4d = 0;
let playing4d = false;
let fps4d = 12;
let acc4d = 0;                // seconds accumulated toward the next frame
let seekGen4d = 0;            // only the latest asynchronous scrub may present a frame
let windowCenter4d = 0;
let inflight4dCount = 0;
const state4d = {
  active: 0, count: 0, playing: false, buffering: false, fps: 12, buffered: 0, error: null,
};
let bufferTarget4d = 0;

function setTimelineBuffering(buffering, targetFrame = active4d) {
  state4d.buffering = Boolean(buffering);
  bufferTarget4d = targetFrame;
  tl.setAttribute("aria-busy", String(state4d.buffering));
  tl.dataset.state = state4d.buffering ? "buffering" : playing4d ? "playing" : "paused";
  const nextText = state4d.buffering && seq4d
    ? `Buffering frame ${bufferTarget4d + 1} of ${seq4d.count}`
    : playing4d ? "Playing" : "Paused";
  if (tlStatus.textContent !== nextText) tlStatus.textContent = nextText;
}

function clear4d() {
  playing4d = false;
  // currentMesh can reference a frame selected for disposal. Clear it so the
  // normal load path does not dispose the frame again.
  const disposingCurrent = currentMesh && [...cache4d.values()].includes(currentMesh);
  for (const m of cache4d.values()) { scene.remove(m); try { m.dispose(); } catch {} }
  cache4d = new Map();
  loading4d = new Map();
  failed4d = new Map();
  seekGen4d++;
  seq4d = null; active4d = 0;
  state4d.active = 0; state4d.count = 0; state4d.playing = false;
  state4d.buffering = false; state4d.buffered = 0; state4d.error = null;
  tlSlider.min = "0"; tlSlider.max = "0"; tlSlider.value = "0";
  tlSlider.setAttribute("aria-valuetext", "Frame 0 of 0");
  tlLabel.textContent = "0 / 0";
  setTimelineBuffering(false);
  if (disposingCurrent) currentMesh = null;
  tl.hidden = true;
}

// Load frame i (idempotent): concurrent callers share one in-flight promise,
// so it is safe to prefetch a window and await a specific frame at once.
function recordFrameFailure4d(failures, i, error) {
  const attempts = (failures.get(i)?.attempts ?? 0) + 1;
  failures.set(i, {
    attempts,
    terminal: attempts >= MAX_FRAME_RETRIES,
    nextRetry: performance.now() + FRAME_RETRY_BASE_MS * (2 ** (attempts - 1)),
    error: String(error),
  });
  console.error(`4D frame ${i} failed (attempt ${attempts}/${MAX_FRAME_RETRIES}):`, error);
}

function loadFrame4d(i, gen) {
  const sequence = seq4d;
  const cache = cache4d;
  const loading = loading4d;
  const failures = failed4d;
  if (!sequence || i < 0 || i >= sequence.count) return Promise.resolve(null);
  if (cache.has(i)) return Promise.resolve(cache.get(i));
  if (loading.has(i)) return loading.get(i);
  const priorFailure = failures.get(i);
  if (priorFailure?.terminal || (priorFailure && performance.now() < priorFailure.nextRetry)) {
    return Promise.resolve(null);
  }
  if (inflight4dCount >= MAX_INFLIGHT_4D_FRAMES) return Promise.resolve(null);
  let mesh;
  let initialized;
  try {
    mesh = new SplatMesh({ url: sequence.base + sequence.frames[i] });
    mesh.quaternion.set(1, 0, 0, 0);
    mesh.visible = false;
    initialized = mesh.initialized;
  } catch (error) {
    try { mesh?.dispose(); } catch {}
    recordFrameFailure4d(failures, i, error);
    return Promise.resolve(null);
  }
  inflight4dCount++;
  const p = Promise.resolve(initialized).then(() => {
    loading.delete(i);
    if (gen !== loadGen || seq4d !== sequence) { try { mesh.dispose(); } catch {} return null; }
    const retained = frameWindow4d(
      windowCenter4d,
      BUF_BEHIND + EVICT_MARGIN,
      BUF_AHEAD + EVICT_MARGIN,
    );
    if (!retained.has(i)) { try { mesh.dispose(); } catch {} return null; }
    failures.delete(i);
    scene.add(mesh);
    cache.set(i, mesh);
    state4d.buffered = cache.size;
    return mesh;
  }).catch((err) => {
    loading.delete(i);
    try { mesh.dispose(); } catch {}
    if (gen !== loadGen || seq4d !== sequence) return null;
    recordFrameFailure4d(failures, i, err);
    return null;
  }).finally(() => {
    inflight4dCount--;
  });
  loading.set(i, p);
  return p;
}

function wrapFrame4d(i) {
  if (!seq4d || seq4d.count < 1) return 0;
  return ((i % seq4d.count) + seq4d.count) % seq4d.count;
}

function frameWindow4d(center, behind, ahead) {
  const indices = new Set();
  if (!seq4d) return indices;
  for (let offset = -behind; offset <= ahead; offset++) {
    indices.add(wrapFrame4d(center + offset));
  }
  return indices;
}

function orderedFrameWindow4d(center, behind, ahead) {
  const indices = [];
  const included = new Set();
  const add = (offset) => {
    const index = wrapFrame4d(center + offset);
    if (!included.has(index)) {
      included.add(index);
      indices.push(index);
    }
  };
  add(0);
  for (let offset = 1; offset <= ahead; offset++) add(offset);
  for (let offset = 1; offset <= behind; offset++) add(-offset);
  return indices;
}

// Ensure the circular window around `center` is loading; evict frames outside
// it. Circularity matters at the sequence boundary: frame 0 must be prefetched
// while the final frame is active or playback stalls forever instead of looping.
function ensureWindow4d(center, gen) {
  if (!seq4d) return;
  windowCenter4d = wrapFrame4d(center);
  const wanted = orderedFrameWindow4d(center, BUF_BEHIND, BUF_AHEAD);
  const retained = frameWindow4d(
    center,
    BUF_BEHIND + EVICT_MARGIN,
    BUF_AHEAD + EVICT_MARGIN,
  );
  for (const i of wanted) loadFrame4d(i, gen);
  for (const [i, m] of [...cache4d]) {
    if (!retained.has(i)) {
      if (m === currentMesh) continue;   // never evict the visible frame
      scene.remove(m); try { m.dispose(); } catch {}
      cache4d.delete(i);
    }
  }
  state4d.buffered = cache4d.size;
}

function present4d(i) {
  const mesh = cache4d.get(i);
  if (!mesh) return false;               // not buffered yet (caller stalls)
  for (const [j, m] of cache4d) m.visible = (j === i);
  currentMesh = mesh;
  active4d = i;
  state4d.active = i;
  tlSlider.value = String(i);
  tlLabel.textContent = `${i + 1} / ${seq4d.count}`;
  tlSlider.setAttribute("aria-valuetext", `Frame ${i + 1} of ${seq4d.count}`);
  setTimelineBuffering(false);
  state.splatCount = splatCountOf(mesh);
  updateHud();
  return true;
}

function play4d() {
  if (seq4d && seq4d.count > 1 && !state4d.error) {
    playing4d = true; state4d.playing = true;
    tlPlay.textContent = "❚❚"; tlPlay.setAttribute("aria-label", "Pause 4D sequence");
    setTimelineBuffering(false);
  }
}
function pause4d() {
  playing4d = false; state4d.playing = false;
  tlPlay.textContent = "▶︎"; tlPlay.setAttribute("aria-label", "Play 4D sequence");
  setTimelineBuffering(false);
}

function reportFrameFailure4d(i) {
  const failure = failed4d.get(i);
  if (!failure?.terminal || state4d.error) return;
  pause4d();
  const message = `Failed to load 4D frame ${i + 1} after ${failure.attempts} attempts.`;
  state4d.error = message;
  state.error = message;
  showError(message, async () => {
    if (!seq4d) return;
    failed4d.delete(i);
    state4d.error = null; state.error = null;
    hideOverlay();
    await seek4dAsync(i);
    if (cache4d.has(i)) play4d();
  }, "Retry", () => {
    state4d.error = null;
    state.error = null;
  }, "4d-frame", "Keep current frame");
}

// Jump to a frame. Wait for its load if the buffer does not contain it.
async function seek4dAsync(i) {
  if (!seq4d) return;
  const gen = loadGen;
  const seek = ++seekGen4d;
  i = ((i % seq4d.count) + seq4d.count) % seq4d.count;
  ensureWindow4d(i, gen);
  if (!cache4d.has(i)) setTimelineBuffering(true, i);
  while (!cache4d.has(i) && gen === loadGen && seek === seekGen4d) {
    await loadFrame4d(i, gen);
    if (cache4d.has(i)) break;
    const failure = failed4d.get(i);
    if (failure?.terminal) { reportFrameFailure4d(i); return; }
    const waitMs = failure
      ? Math.max(0, failure.nextRetry - performance.now())
      : 25;
    await new Promise((resolve) => setTimeout(resolve, waitMs));
  }
  if (gen !== loadGen || seek !== seekGen4d) return;
  if (present4d(i)) ensureWindow4d(i, gen);
}

async function readBoundedUtf8(response, maxBytes) {
  const declaredLength = Number(response.headers.get("content-length"));
  if (Number.isFinite(declaredLength) && declaredLength > maxBytes) {
    throw new Error(`response exceeds ${formatBytes(maxBytes)}`);
  }
  if (!response.body) {
    const bytes = await response.arrayBuffer();
    if (bytes.byteLength > maxBytes) throw new Error(`response exceeds ${formatBytes(maxBytes)}`);
    return new TextDecoder("utf-8", { fatal: true }).decode(bytes);
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder("utf-8", { fatal: true });
  const parts = [];
  let received = 0;
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      received += value.byteLength;
      if (received > maxBytes) {
        await reader.cancel();
        throw new Error(`response exceeds ${formatBytes(maxBytes)}`);
      }
      parts.push(decoder.decode(value, { stream: true }));
    }
    parts.push(decoder.decode());
  } catch (error) {
    try { await reader.cancel(); } catch {}
    throw error;
  }
  return parts.join("");
}

async function load4DSequence(def) {
  const gen = ++loadGen;
  detachProgressiveMesh();
  state.loading = true; state.error = null; state.rendered = false;
  frameCountSinceLoad = 0;
  const overlayTicket = showOverlay(`Loading ${def.label}…`);

  const dismissCandidateError = () => {
    state.error = null;
    state.inputError = null;
  };
  const candidateDismiss = () => currentMesh && currentScene
    ? dismissCandidateError
    : null;
  const retryCandidate = () => loadScene(def.id).catch(console.error);

  const base = SPLAT_DIR + def.manifest.replace(/[^/]+$/, "");
  let manifest;
  try {
    const response = await fetch(SPLAT_DIR + def.manifest);
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    manifest = JSON.parse(await readBoundedUtf8(response, MAX_4D_MANIFEST_BYTES));
  } catch (err) {
    if (gen !== loadGen) return null;
    state.loading = false; state.error = String(err);
    console.error("Failed to load 4D manifest for " + def.label + ":", err);
    showError("Failed to load the 4D manifest for " + def.label + ".",
      retryCandidate, "Retry", candidateDismiss());
    throw err;
  }
  if (gen !== loadGen) return null;
  const frames = manifest?.frames;
  const manifestFps = manifest?.fps ?? 12;
  const portableFrameNames = Array.isArray(frames)
    ? frames.map((frame) => typeof frame === "string" ? frame.toLowerCase() : "")
    : [];
  if (!Array.isArray(frames) || frames.length === 0 || frames.length > MAX_4D_FRAMES ||
      !frames.every((frame) => typeof frame === "string" &&
        /^[A-Za-z0-9][A-Za-z0-9._-]*\.(ply|spz)$/i.test(frame)) ||
      new Set(portableFrameNames).size !== portableFrameNames.length) {
    state.loading = false; state.error = "invalid 4D manifest frames";
    showError("Invalid 4D manifest for " + def.label,
      retryCandidate, "Retry", candidateDismiss());
    throw new Error("invalid 4D manifest frames");
  }
  if (!Number.isFinite(manifestFps) || manifestFps <= 0 || manifestFps > 240) {
    state.loading = false; state.error = "invalid 4D manifest fps";
    showError("Invalid 4D playback rate for " + def.label,
      retryCandidate, "Retry", candidateDismiss());
    throw new Error("invalid 4D manifest fps");
  }
  // Stage frame zero independently. The active static/4D scene and its cache
  // remain untouched until the candidate manifest and first frame both pass.
  while (inflight4dCount >= MAX_INFLIGHT_4D_FRAMES && gen === loadGen) {
    await new Promise((resolve) => setTimeout(resolve, 25));
  }
  if (gen !== loadGen) return null;
  let first = null;
  try {
    first = new SplatMesh({ url: base + frames[0] });
    first.quaternion.set(1, 0, 0, 0);
    first.visible = false;
    inflight4dCount++;
    try {
      await first.initialized;
    } finally {
      inflight4dCount--;
    }
  } catch (err) {
    try { first?.dispose(); } catch {}
    if (gen !== loadGen) return null;
    state.loading = false; state.error = String(err);
    console.error("Failed to load the first 4D frame for " + def.label + ":", err);
    showError("Failed to load the first 4D frame of " + def.label + ".",
      retryCandidate, "Retry", candidateDismiss());
    throw err;
  }
  if (gen !== loadGen) { try { first?.dispose(); } catch {} return null; }

  // Commit the candidate in one swap. clear4d() disposes an old temporal
  // cache; a normal current mesh is removed immediately afterward.
  clear4d();
  if (currentMesh) { scene.remove(currentMesh); try { currentMesh.dispose(); } catch {} }
  currentMesh = null;
  fps4d = manifestFps; state4d.fps = fps4d;
  seq4d = { base, frames: [...frames], count: frames.length };
  cache4d = new Map([[0, first]]);
  loading4d = new Map(); failed4d = new Map();
  state4d.count = seq4d.count; state4d.buffered = 1;
  scene.add(first);
  currentScene = def;
  state.scene = def.id; state.format = def.fmt;
  state.source = "bundled"; state.fileBytes = null; state.inputError = null;
  present4d(0);
  frameMesh(first);
  orbitEnabled = !reducedMotion.matches; manualControl = false; activeCameraView = null;
  syncOrbitBtn(); syncCameraButtons();
  ensureWindow4d(0, gen);

  tlSlider.min = "0"; tlSlider.max = String(seq4d.count - 1); tlSlider.value = "0";
  tl.hidden = false;
  acc4d = 0;
  if (reducedMotion.matches) pause4d(); else play4d();

  state.loading = false;
  frameCountSinceLoad = 0;
  updateHud(); updateSceneButtons();
  syncSceneURL(def);
  if (!hideOverlay(overlayTicket)) makeLocalErrorDismissible();
  return seq4d;
}

tlPlay.addEventListener("click", () => (playing4d ? pause4d() : play4d()));
tlSlider.addEventListener("input", () => {
  const frame = Number(tlSlider.value);
  tlSlider.setAttribute("aria-valuetext", `Frame ${frame + 1} of ${state4d.count}`);
  tlLabel.textContent = `${frame + 1} / ${state4d.count}`;
  pause4d();
  seek4dAsync(frame);
});

// ---------------------------------------------------------------------------
// HUD + UI
// ---------------------------------------------------------------------------
const hScene = document.getElementById("h-scene");
const hFmt = document.getElementById("h-fmt");
const hSource = document.getElementById("h-source");
const hSplats = document.getElementById("h-splats");
const hFps = document.getElementById("h-fps");
const hCam = document.getElementById("h-cam");
const hMode = document.getElementById("h-mode");

function setHudValue(element, label, value, { strong = true, numeric = false } = {}) {
  const valueElement = document.createElement(strong ? "b" : "span");
  valueElement.className = `${strong ? "" : "dim"}${numeric ? " num" : ""}`.trim();
  valueElement.textContent = value;
  element.replaceChildren(document.createTextNode(label + ": "), valueElement);
}
function updateHud() {
  setHudValue(hScene, "scene", currentScene?.label ?? "—");
  hScene.title = currentScene?.label ?? "";
  setHudValue(hFmt, "format", currentScene?.fmt ?? "—");
  const source = state.source === "local"
    ? `local · ${formatBytes(state.fileBytes)}`
    : state.source ?? "—";
  setHudValue(hSource, "source", source, { numeric: state.source === "local" });
  setHudValue(hSplats, "splats", state.splatCount > 0 ? formatCount(state.splatCount) : "—",
    { numeric: true });
}
function updateCamHud() {
  setHudValue(hFps, "fps", Number.isFinite(state.fps) ? state.fps.toFixed(0) : "—", { numeric: true });
  const position = [camera.position.x, camera.position.y, camera.position.z]
    .map((value) => Number.isFinite(value) ? value.toFixed(2) : "—")
    .join(", ");
  setHudValue(hCam, "cam", position, { strong: false, numeric: true });
  setHudValue(hMode, "mode", manualControl ? "manual" : orbitEnabled ? "orbit" : "static");
}

const scenesEl = document.getElementById("scenes");
function visibleSceneDefinitions() {
  return localSceneDef ? [localSceneDef, ...SCENES] : SCENES;
}
function buildSceneButtons() {
  for (const button of scenesEl.querySelectorAll("button[data-scene]")) button.remove();
  for (const s of visibleSceneDefinitions()) {
    const b = document.createElement("button");
    b.type = "button";
    b.dataset.scene = s.id;
    b.title = s.label;
    const title = document.createElement("span");
    title.className = "scene-title";
    title.textContent = s.label;
    b.append(title);
    const meta = document.createElement("span");
    meta.className = "meta";
    meta.textContent = `${s.fmt} · ${s.note}`;
    b.append(meta);
    b.addEventListener("click", () => loadScene(s.id).catch((e) => console.error(e)));
    scenesEl.appendChild(b);
  }
}
function updateSceneButtons() {
  for (const b of scenesEl.querySelectorAll("button[data-scene]")) {
    const active = b.dataset.scene === (currentScene && currentScene.id);
    b.classList.toggle("active", active);
    b.setAttribute("aria-pressed", String(active));
  }
}

// ---------------------------------------------------------------------------
// Local-first open workflow. File bytes stay in the browser/webview: Spark
// decodes a fresh File stream directly, with no blob URL, upload, or filesystem
// permission. Retain only the newest File so switching scenes does not pin an
// unbounded history of user data in memory.
// ---------------------------------------------------------------------------
const localFileInput = document.getElementById("localFileInput");
const dropTarget = document.getElementById("dropTarget");
let dragDepth = 0;

function showLocalFileError(message) {
  state.inputError = message;
  const canDismiss = Boolean(currentMesh && currentScene);
  state.error = canDismiss ? null : message;
  showError(message, () => openLocalFilePickerFromError(), "Choose another file",
    canDismiss ? () => { state.inputError = null; } : null, "local-input");
}

function makeLocalErrorDismissible() {
  if (!errorDialogOpen || overlayErrorKind !== "local-input" || overlayDismiss ||
      !currentMesh || !currentScene) return;
  overlayDismiss = () => { state.inputError = null; };
  ovDismiss.hidden = false;
}

function openLocalFilePickerFromError() {
  const wasInert = scenesEl.inert;
  scenesEl.inert = false;
  localFileInput.click();
  scenesEl.inert = wasInert;
}

async function openLocalFile(file) {
  if (!renderAvailable) return null;
  const openGeneration = ++localOpenGen;
  ++loadGen;
  detachProgressiveMesh();
  state.loading = true;
  state.error = null;
  const overlayTicket = showOverlay("Checking local file…");
  let descriptor;
  try {
    descriptor = await validateLocalFile(file, LOCAL_FILE_TYPES);
  } catch (error) {
    if (openGeneration !== localOpenGen) return null;
    state.loading = false;
    showLocalFileError(error instanceof Error ? error.message : String(error));
    return null;
  }
  if (openGeneration !== localOpenGen) return null;
  if (overlayTicket !== overlayGeneration) {
    state.loading = false;
    return null;
  }

  const candidate = {
    id: "local-file",
    label: file.name,
    fmt: descriptor.fmt,
    note: `${formatBytes(file.size)} · local only`,
    localFile: file,
    fileType: descriptor.type,
  };
  pendingLocalSceneDef = candidate;
  return loadScene(candidate.id, candidate);
}

localFileInput.addEventListener("change", () => {
  const file = localFileInput.files?.[0] ?? null;
  localFileInput.value = ""; // allow selecting the same file again
  if (file) openLocalFile(file).catch((error) => console.error(error));
});

function dragHasFiles(event) {
  return Array.from(event.dataTransfer?.types ?? []).includes("Files");
}
function setDropTargetVisible(visible) {
  dropTarget.hidden = !visible;
}
window.addEventListener("dragenter", (event) => {
  if (!dragHasFiles(event)) return;
  event.preventDefault();
  if (!renderAvailable) return;
  dragDepth++;
  setDropTargetVisible(true);
});
window.addEventListener("dragover", (event) => {
  if (!dragHasFiles(event)) return;
  event.preventDefault();
  if (event.dataTransfer) event.dataTransfer.dropEffect = "copy";
});
window.addEventListener("dragleave", (event) => {
  if (dragDepth === 0) return;
  event.preventDefault();
  dragDepth = Math.max(0, dragDepth - 1);
  if (dragDepth === 0) setDropTargetVisible(false);
});
window.addEventListener("drop", (event) => {
  if (!dragHasFiles(event)) return;
  event.preventDefault();
  dragDepth = 0;
  setDropTargetVisible(false);
  if (!renderAvailable) return;
  const files = Array.from(event.dataTransfer?.files ?? []);
  if (files.length !== 1) {
    showLocalFileError("Drop one splat file at a time.");
    return;
  }
  openLocalFile(files[0]).catch((error) => console.error(error));
});
window.addEventListener("keydown", (event) => {
  if (event.key === "Escape" && !dropTarget.hidden) {
    dragDepth = 0;
    setDropTargetVisible(false);
  }
});

function syncOrbitBtn() {
  const button = document.getElementById("orbitBtn");
  button.textContent = "Orbit: " + (orbitEnabled ? "on" : "off");
  button.setAttribute("aria-pressed", String(orbitEnabled));
}

function syncCameraButtons() {
  for (const button of document.querySelectorAll("#bar [data-cam]")) {
    button.setAttribute("aria-pressed", String(button.dataset.cam === activeCameraView));
  }
}

function clearNamedCameraView() {
  activeCameraView = null;
  syncCameraButtons();
}

const helpButton = document.getElementById("helpBtn");
const helpClose = document.getElementById("helpClose");
helpButton.addEventListener("click", () => {
  helpDialog.showModal();
  helpDialog.focus({ preventScroll: true });
  helpDialog.scrollTop = 0;
});
helpClose.addEventListener("click", () => helpDialog.close());

document.querySelectorAll("#bar [data-cam]").forEach((b) => b.addEventListener("click", () => setView(b.dataset.cam)));
document.getElementById("orbitBtn").addEventListener("click", () => {
  orbitEnabled = !orbitEnabled; manualControl = false; clearNamedCameraView(); syncOrbitBtn();
});
document.getElementById("resetBtn").addEventListener("click", () => {
  if (currentMesh) {
    orbitEnabled = !reducedMotion.matches;
    manualControl = false;
    clearNamedCameraView();
    syncOrbitBtn();
    frameMesh(currentMesh);
  }
});
const cameraToolbar = document.getElementById("bar");
const cameraToolbarButtons = [...cameraToolbar.querySelectorAll("button")];
function setToolbarTabStop(activeButton) {
  for (const button of cameraToolbarButtons) button.tabIndex = button === activeButton ? 0 : -1;
}
setToolbarTabStop(cameraToolbarButtons[0]);
cameraToolbar.addEventListener("focusin", (event) => {
  if (event.target.matches("button")) setToolbarTabStop(event.target);
});
cameraToolbar.addEventListener("keydown", (event) => {
  if (!event.target.matches("button")) return;
  if (!["ArrowLeft", "ArrowRight", "Home", "End"].includes(event.key)) return;
  const buttons = cameraToolbarButtons.filter((button) => !button.disabled);
  const current = buttons.indexOf(event.target);
  let next = current;
  if (event.key === "ArrowLeft") next = (current - 1 + buttons.length) % buttons.length;
  if (event.key === "ArrowRight") next = (current + 1) % buttons.length;
  if (event.key === "Home") next = 0;
  if (event.key === "End") next = buttons.length - 1;
  event.preventDefault();
  setToolbarTabStop(buttons[next]);
  buttons[next].focus();
});

// Any direct interaction on the canvas switches to manual (SparkControls) navigation.
renderer.domElement.addEventListener("pointerdown", () => {
  manualControl = true; orbitEnabled = false; clearNamedCameraView(); syncOrbitBtn();
});
renderer.domElement.addEventListener("wheel", () => {
  manualControl = true; orbitEnabled = false; clearNamedCameraView(); syncOrbitBtn();
}, { passive: true });
renderer.domElement.addEventListener("keydown", (event) => {
  if (["ArrowUp", "ArrowDown", "ArrowLeft", "ArrowRight", "w", "a", "s", "d", "q", "e", "W", "A", "S", "D", "Q", "E"].includes(event.key)) {
    manualControl = true; orbitEnabled = false; clearNamedCameraView(); syncOrbitBtn();
  }
});
renderer.domElement.addEventListener("webglcontextlost", (event) => {
  event.preventDefault();
  if (!renderAvailable) return;
  renderAvailable = false;
  ++localOpenGen;
  ++loadGen;
  cancelLocalFileValidation();
  detachProgressiveMesh();
  pause4d();
  state.loading = false;
  state.error = "WebGL context lost";
  showError("Rendering stopped because the WebGL context was lost.",
    () => location.reload(), "Reload", null, "render-fatal");
});
renderer.domElement.addEventListener("webglcontextrestored", () => location.reload());
reducedMotion.addEventListener("change", (event) => {
  if (event.matches) {
    orbitEnabled = false;
    pause4d();
    syncOrbitBtn();
  }
});

// ---------------------------------------------------------------------------
// Render loop
// ---------------------------------------------------------------------------
const state = {
  ready: false, loading: false, rendered: false, error: null,
  scene: null, format: null, source: null, fileBytes: null,
  splatCount: 0, fps: 0, inputError: null,
  progressive: false,  // true when the last load streamed splats in progressively
};

let lastT = performance.now();
let fpsAccum = 0, fpsFrames = 0;
const clock = new THREE.Clock();
const cameraDirection = new THREE.Vector3();

renderer.setAnimationLoop(() => {
  const now = performance.now();
  const dt = clock.getDelta();

  if (manualControl) {
    controls.update(camera);
    target.copy(camera.position).add(camera.getWorldDirection(cameraDirection).multiplyScalar(orbitRadius));
  } else if (orbitEnabled) {
    orbitAzimuth += ORBIT_SPEED * dt;
    applyOrbit();
  }

  // 4D temporal playback: advance to the next frame at the manifest fps,
  // Playback stalls if the next frame in the window is not ready.
  if (playing4d && seq4d && seq4d.count > 1) {
    acc4d += dt;
    const step = 1 / fps4d;
    if (acc4d >= step) {
      const next = (active4d + 1) % seq4d.count;
      ensureWindow4d(active4d, loadGen);   // circular prefetch around the playhead
      if (cache4d.has(next)) { acc4d %= step; present4d(next); }
      else {
        acc4d = step;                       // hold at threshold until buffered
        setTimelineBuffering(true, next);
        reportFrameFailure4d(next);
      }
    }
  }

  renderer.render(scene, camera);

  if (currentMesh && !state.loading && !state.rendered) {
    frameCountSinceLoad++;
    if (frameCountSinceLoad >= 4) state.rendered = true; // a few frames -> splat sort has run
  }

  // fps (smoothed over ~0.25s)
  const frameMs = now - lastT; lastT = now;
  fpsAccum += frameMs; fpsFrames++;
  if (fpsAccum >= 250) { state.fps = 1000 / (fpsAccum / fpsFrames); fpsAccum = 0; fpsFrames = 0; updateCamHud(); }
});

window.addEventListener("resize", () => {
  const width = Math.max(window.innerWidth, 1);
  const height = Math.max(window.innerHeight, 1);
  camera.aspect = width / height;
  camera.updateProjectionMatrix();
  renderer.setSize(width, height);
});

// ---------------------------------------------------------------------------
// Boot + Playwright/automation hooks
// ---------------------------------------------------------------------------
updateHud();
syncOrbitBtn();
syncCameraButtons();

window.__viewer = {
  THREE, scene, camera, renderer, spark,
  state,
  get scenes() { return visibleSceneDefinitions().map((s) => ({ id: s.id, label: s.label, file: s.file, fmt: s.fmt, temporal: !!s.temporal, local: !!s.localFile })); },
  async load(id) { return loadScene(id); },
  async openFile(file) { return openLocalFile(file); },
  // 4D temporal player controls (no-ops when not in a 4D scene).
  play4D() { play4d(); },
  pause4D() { pause4d(); },
  async seek4D(i) { pause4d(); return seek4dAsync(i); },
  get4DState() {
    return {
      ...state4d,
      inFlight: inflight4dCount,
      maxInFlight: MAX_INFLIGHT_4D_FRAMES,
    };
  },
  setView,
  setOrbit(on) {
    orbitEnabled = !!on; manualControl = false; clearNamedCameraView(); syncOrbitBtn();
  },
  setAngles(azDeg, elDeg, distFactor) {
    orbitEnabled = false; manualControl = false; clearNamedCameraView(); syncOrbitBtn();
    orbitAzimuth = THREE.MathUtils.degToRad(azDeg);
    orbitElevation = THREE.MathUtils.degToRad(elDeg);
    if (distFactor) orbitRadius *= distFactor;
    applyOrbit();
  },
  getStats() {
    return {
      ready: state.ready, loading: state.loading, rendered: state.rendered, error: state.error,
      inputError: state.inputError, scene: state.scene, format: state.format, source: state.source,
      fileBytes: state.fileBytes, splatCount: state.splatCount, fps: state.fps,
      camera: camera.position.toArray().map((n) => +n.toFixed(3)),
      target: target.toArray().map((n) => +n.toFixed(3)),
    };
  },
  // Resolves once the requested scene is loaded AND a few frames have rendered.
  async waitRendered(timeoutMs = 60000) {
    const t0 = performance.now();
    while (performance.now() - t0 < timeoutMs) {
      if (state.error) throw new Error(state.error);
      if (!state.loading && currentMesh && state.rendered) return this.getStats();
      await new Promise((r) => setTimeout(r, 50));
    }
    throw new Error("waitRendered timeout");
  },
};

async function readPackagedSceneIndex() {
  try {
    const response = await fetch("./public/scene-index.json");
    if (!response.ok) return null;
    const index = JSON.parse(await readBoundedUtf8(response, 64 * 1024));
    const knownIds = new Set(SCENES.map((sceneDef) => sceneDef.id));
    if (index?.version !== 1 || !Array.isArray(index.scenes) ||
        !index.scenes.every((id) => typeof id === "string" && knownIds.has(id)) ||
        new Set(index.scenes).size !== index.scenes.length) {
      throw new Error("invalid packaged scene index");
    }
    return new Set(index.scenes);
  } catch (error) {
    console.warn("Could not read the packaged scene index:", error);
    return null;
  }
}

// Use the packaged index when it exists. The development server falls back to
// HEAD probes because external fixtures are optional and remain outside packages.
(async () => {
  const packagedScenes = await readPackagedSceneIndex();
  let availableScenes;
  if (packagedScenes) {
    availableScenes = SCENES.filter((sceneDef) => packagedScenes.has(sceneDef.id));
  } else {
    const ok = await Promise.all(SCENES.map(async (s) => {
      const url = SPLAT_DIR + (s.temporal ? s.manifest : s.file);
      try { return (await fetch(url, { method: "HEAD" })).ok; } catch { return false; }
    }));
    availableScenes = SCENES.filter((_, index) => ok[index]);
  }
  SCENES.splice(0, SCENES.length, ...availableScenes);
  buildSceneButtons();
  state.ready = true;
  const requestedScene = new URLSearchParams(window.location.search).get("scene");
  const initialScene = SCENES.find((sceneDef) => sceneDef.id === requestedScene) ?? SCENES[0];
  if (initialScene) {
    loadScene(initialScene.id).catch((error) => console.error(error));
  } else {
    const message = "No bundled scene is available. Run the asset setup or open a local splat.";
    state.error = message;
    showError(message, () => openLocalFilePickerFromError(), "Open local splat");
  }
})();
