#!/usr/bin/env python3
"""Generate NOTICE and THIRD_PARTY_LICENSES.md from the dependency manifests.

Hand-maintained notice files rot. They keep listing a dependency after it is removed, and
they miss one after it is added — and both failures are invisible until someone audits the
release, which is exactly when it is most expensive to discover. Before this program,
`NOTICE` still credited `ml-sharp`, a snapshot that contributed nothing to the build.

So notices are generated, and CI runs this in ``--check`` mode and fails on drift.

Two distinct outputs, because they answer two different questions:

``NOTICE``
    What is *compiled into the artifact you downloaded*. This is the file whose accuracy is
    a license obligation. It lists only dependencies that are actually linked into the core.

``THIRD_PARTY_LICENSES.md``
    Everything third-party the *repository* touches, including external tools that Melkor
    merely invokes and does not redistribute. It is documentation, not an obligation.

Keeping these separate matters. Listing an external AGPL trainer in `NOTICE` would imply
Melkor ships it. It does not: the adapter invokes a program the user installed themselves.

Usage::

    python3 tools/generate_notices.py --write
    python3 tools/generate_notices.py --check    # CI
"""

from __future__ import annotations

import argparse
import difflib
import json
import math
import os
import stat
import sys
import tempfile
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
LOCK_PATH = REPO_ROOT / "third_party" / "manifest.lock.json"
SPEC_LOCK_PATH = REPO_ROOT / "third_party" / "specifications.lock.json"
ADAPTERS_DOC = "docs/adapters/index.md"

NOTICE_PATH = REPO_ROOT / "NOTICE"
THIRD_PARTY_PATH = REPO_ROOT / "THIRD_PARTY_LICENSES.md"

GENERATED_BANNER = (
    "This file is generated by tools/generate_notices.py from\n"
    "the third-party lock files. Do not edit it by hand. Edit the locks and\n"
    "regenerate. CI fails if this file drifts from the locks."
)
MAX_INPUT_BYTES = 4 * 1024 * 1024


def read_bounded_text(path: Path) -> str:
    """Read one bounded regular UTF-8 file."""

    if path.is_symlink():
        raise ValueError(f"input must not be a symbolic link: {path}")
    flags = os.O_RDONLY | getattr(os, "O_BINARY", 0) | getattr(os, "O_CLOEXEC", 0)
    flags |= getattr(os, "O_NOFOLLOW", 0)
    try:
        descriptor = os.open(path, flags)
        with os.fdopen(descriptor, "rb") as handle:
            initial = os.fstat(handle.fileno())
            if not stat.S_ISREG(initial.st_mode) or initial.st_size > MAX_INPUT_BYTES:
                raise ValueError(f"input must be a bounded regular file: {path}")
            raw = handle.read(MAX_INPUT_BYTES + 1)
            final = os.fstat(handle.fileno())
            if (
                len(raw) > MAX_INPUT_BYTES
                or len(raw) != initial.st_size
                or final.st_dev != initial.st_dev
                or final.st_ino != initial.st_ino
                or final.st_size != initial.st_size
                or final.st_mtime_ns != initial.st_mtime_ns
                or final.st_ctime_ns != initial.st_ctime_ns
            ):
                raise ValueError(f"input changed or exceeded its size limit: {path}")
        return raw.decode("utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        raise ValueError(f"cannot read UTF-8 input: {path}") from exc


def strict_json(path: Path) -> Any:
    """Read UTF-8 JSON and reject duplicate object names."""

    def object_without_duplicates(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
        value: dict[str, Any] = {}
        for name, item in pairs:
            if name in value:
                raise ValueError(f"duplicate object name {name!r}")
            value[name] = item
        return value

    def reject_constant(value: str) -> None:
        raise ValueError(f"non-JSON number {value!r}")

    def finite_float(value: str) -> float:
        parsed = float(value)
        if not math.isfinite(parsed):
            raise ValueError(f"non-finite JSON number {value!r}")
        return parsed

    try:
        return json.loads(
            read_bounded_text(path),
            object_pairs_hook=object_without_duplicates,
            parse_constant=reject_constant,
            parse_float=finite_float,
        )
    except RecursionError as exc:
        raise ValueError("JSON nesting is too deep") from exc


def load_lock() -> dict:
    lock = strict_json(LOCK_PATH)
    if not isinstance(lock, dict) or not isinstance(lock.get("dependencies"), list):
        raise ValueError("the dependency lock is invalid")
    return lock


def load_specifications() -> list[dict[str, Any]]:
    lock = strict_json(SPEC_LOCK_PATH)
    if (
        not isinstance(lock, dict)
        or lock.get("schema_version") != 1
        or not isinstance(lock.get("specifications"), list)
    ):
        raise ValueError("the specification lock is invalid")
    specifications = lock["specifications"]
    for index, spec in enumerate(specifications):
        if not isinstance(spec, dict):
            raise ValueError(f"specification {index} must be an object")
        for name in (
            "id",
            "license",
            "license_notice_file",
            "upstream",
            "commit",
        ):
            if not isinstance(spec.get(name), str) or not spec[name]:
                raise ValueError(f"specification {index} requires {name}")
    return specifications


def iter_shipped(lock: dict):
    """Dependencies whose code is compiled into Melkor's own artifacts.

    Yield each dependency and each embedded dependency. An embedded dependency needs
    its own notice because the parent license does not cover it.
    """
    for dep in lock["dependencies"]:
        yield {
            "id": dep["id"],
            "license": dep["license"],
            "upstream": dep["upstream"],
            "revision": dep["revision"],
            "release": dep.get("release"),
            "license_file": dep.get("license_file"),
            "purpose": dep.get("purpose", ""),
            "patches": dep.get("patches", []),
            "build_condition": dep.get("build_condition", "always"),
        }
        for embedded in dep.get("embeds", []):
            yield {
                "id": embedded["id"],
                "license": embedded["license"],
                "upstream": embedded["upstream"],
                "revision": None,
                "release": embedded.get("version"),
                "license_file": embedded.get("license_file"),
                "purpose": embedded.get("purpose", ""),
                "patches": [],
                "embedded_in": dep["id"],
                "build_condition": dep.get("build_condition", "always"),
            }


def render_notice(
    lock: dict, specifications: list[dict[str, Any]] | None = None
) -> str:
    lines: list[str] = []
    lines.append("Melkor")
    lines.append("Copyright (c) Sepehr Mahmoudian")
    lines.append("")
    lines.append("Licensed under the MIT License. See LICENSE.")
    lines.append("")
    for line in GENERATED_BANNER.splitlines():
        lines.append(line)
    lines.append("")
    lines.append("=" * 78)
    lines.append("")
    lines.append("Third-party code used by Melkor artifacts")
    lines.append("")
    lines.append("The source bundle contains all these components.")
    lines.append("A binary contains a component only when its build condition applies.")
    lines.append("Each license applies only to the code that it covers.")
    lines.append("")

    for dep in iter_shipped(lock):
        lines.append("-" * 78)
        lines.append("")
        header = dep["id"]
        if dep.get("embedded_in"):
            header += f"  (embedded in {dep['embedded_in']})"
        lines.append(header)
        lines.append("")
        if dep["purpose"]:
            lines.append(f"  Purpose:  {dep['purpose']}")
        lines.append(f"  License:  {dep['license']}")
        lines.append(f"  Build condition: {dep['build_condition']}")
        lines.append(f"  Upstream: {dep['upstream']}")
        if dep["release"]:
            lines.append(f"  Version:  {dep['release']}")
        if dep["revision"]:
            lines.append(f"  Revision: {dep['revision']}")
        if dep["license_file"]:
            lines.append(f"  License source: {dep['license_file']}")
            lines.append(f"  Installed license: licenses/{dep['id']}-LICENSE")
        if dep["patches"]:
            lines.append("")
            lines.append(
                f"  Modified by Melkor. {len(dep['patches'])} local "
                f"patch{'es' if len(dep['patches']) != 1 else ''} "
                f"under third_party/patches/{dep['id']}/:"
            )
            for patch in dep["patches"]:
                lines.append(f"    - {patch['file']}")
        lines.append("")

    if specifications:
        lines.append("=" * 78)
        lines.append("")
        lines.append("Third-party specifications in the Melkor source bundle")
        lines.append("")
        lines.append("The binary package does not include these specification files.")
        lines.append("")
        for spec in specifications:
            lines.append("-" * 78)
            lines.append("")
            lines.append(str(spec["id"]))
            lines.append("")
            lines.append(f"  License:  {spec['license']}")
            lines.append(f"  Upstream: {spec['upstream']}")
            lines.append(f"  Revision: {spec['commit']}")
            lines.append(f"  License notice: {spec['license_notice_file']}")
            lines.append("")

    lines.append("=" * 78)
    lines.append("")
    lines.append("External tools invoked but NOT redistributed")
    lines.append("")
    lines.append("Melkor adapters run external programs that the user installs separately.")
    lines.append("Melkor does not ship their source or model weights.")
    lines.append("Their licenses are not the Melkor license.")
    lines.append("Each adapter records its license restrictions.")
    lines.append("")
    lines.append(f"See {ADAPTERS_DOC}.")
    lines.append("")
    return "\n".join(lines)


def render_third_party(
    lock: dict, specifications: list[dict[str, Any]] | None = None
) -> str:
    lines: list[str] = []
    lines.append("# Third-party licenses")
    lines.append("")
    lines.append("<!--")
    for line in GENERATED_BANNER.splitlines():
        lines.append(line)
    lines.append("-->")
    lines.append("")
    lines.append("Melkor uses the MIT License.")
    lines.append("This file lists each third-party component that the repository uses.")
    lines.append("It separates redistributed content from external programs.")
    lines.append("")
    lines.append("## Used by Melkor artifacts")
    lines.append("")
    lines.append("The source bundle contains all these components.")
    lines.append("A binary contains a component only when its build condition applies.")
    lines.append("`third_party/manifest.lock.json` records each upstream review target.")
    lines.append("`tools/verify_third_party.py` verifies vendored digests and declared patches in CI.")
    lines.append("")
    lines.append("| Component | License | Build condition | Version | Upstream |")
    lines.append("|---|---|---|---|---|")
    for dep in iter_shipped(lock):
        name = dep["id"]
        if dep.get("embedded_in"):
            name = f"{name} <sub>(in {dep['embedded_in']})</sub>"
        version = dep["release"] or (dep["revision"][:12] if dep["revision"] else "—")
        lines.append(
            f"| {name} | {dep['license']} | `{dep['build_condition']}` | {version} | "
            f"<{dep['upstream']}> |"
        )
    lines.append("")

    for dep in iter_shipped(lock):
        if not dep["patches"]:
            continue
        lines.append(f"### Modifications to {dep['id']}")
        lines.append("")
        lines.append(
            f"Melkor applies local patches to upstream `{dep['revision'][:12]}`. "
            f"The patch files are in `third_party/patches/{dep['id']}/`."
        )
        lines.append("")
        for patch in dep["patches"]:
            # The verifier rejects a missing rationale. Keep generation diagnostic-safe.
            rationale = patch.get("rationale") or "(no rationale recorded — see the lock)"
            lines.append(f"- **`{patch['file']}`** — {rationale}")
            lines.append(f"  Upstream status: {patch.get('upstream_status', 'unknown')}.")
        lines.append("")

    if specifications:
        lines.append("## Specifications in the source bundle")
        lines.append("")
        lines.append("The source bundle includes the pinned specification files below.")
        lines.append("The binary package does not include these files.")
        lines.append("")
        lines.append("| Specification | License | Revision | Upstream |")
        lines.append("|---|---|---|---|")
        for spec in specifications:
            revision = str(spec["commit"])
            lines.append(
                f"| {spec['id']} | {spec['license']} | `{revision[:12]}` | "
                f"[{spec['upstream']}]({spec['upstream']}) |"
            )
        lines.append("")
        for spec in specifications:
            lines.append(
                f"The full {spec['id']} copyright and license notice is in "
                f"`{spec['license_notice_file']}`."
            )
            lines.append("")

    lines.append("## Invoked but not redistributed")
    lines.append("")
    lines.append("Reconstruction, training, and depth systems are separate programs.")
    lines.append("Melkor does not vendor their source or model weights.")
    lines.append("Adapter manifests record code and model-weight licenses separately.")
    lines.append("")
    lines.append(
        f"[{ADAPTERS_DOC}]({ADAPTERS_DOC}) documents the upstream projects and licenses."
    )
    lines.append("")
    lines.append("## Viewer dependencies")
    lines.append("")
    lines.append("`viewer/package-lock.json` locks the viewer test and build tools.")
    lines.append("`viewer/fetch-assets.sh` pins browser runtime URLs and SHA-256 digests.")
    lines.append("`viewer/src-tauri/Cargo.lock` locks the desktop dependencies.")
    lines.append("`viewer/RUST_THIRD_PARTY_LICENSES.html` contains the Rust license inventory.")
    lines.append("`cargo-deny` enforces the Rust license policy in CI.")
    lines.append("")
    return "\n".join(lines)


def compare(path: Path, expected: str) -> list[str]:
    actual = read_bounded_text(path) if path.is_file() else ""
    if actual == expected:
        return []
    diff = difflib.unified_diff(
        actual.splitlines(keepends=True),
        expected.splitlines(keepends=True),
        fromfile=f"{path.name} (committed)",
        tofile=f"{path.name} (generated)",
        n=1,
    )
    return list(diff)


def atomic_write_text(path: Path, content: str) -> None:
    """Replace a generated file only after the complete write succeeds."""
    if path.is_symlink():
        raise ValueError(f"generated output must not be a symbolic link: {path}")
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        temporary.chmod(path.stat().st_mode & 0o777 if path.exists() else 0o644)
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="regenerate the notice files")
    mode.add_argument("--check", action="store_true", help="fail if the committed files drift")
    args = parser.parse_args()

    try:
        lock = load_lock()
        specifications = load_specifications()
        outputs = {
            NOTICE_PATH: render_notice(lock, specifications),
            THIRD_PARTY_PATH: render_third_party(lock, specifications),
        }
    except (KeyError, OSError, TypeError, ValueError) as error:
        print(f"error: cannot generate notices: {error}", file=sys.stderr)
        return 2

    if args.write:
        for path, content in outputs.items():
            atomic_write_text(path, content)
            print(f"wrote {path.relative_to(REPO_ROOT)}")
        return 0

    failed = False
    for path, content in outputs.items():
        diff = compare(path, content)
        if diff:
            failed = True
            print(
                f"{path.relative_to(REPO_ROOT)} does not match the dependency lock files:",
                file=sys.stderr,
            )
            sys.stderr.writelines(diff)
            print(file=sys.stderr)

    if failed:
        print(
            "Notice files are stale. Run:\n"
            "    python3 tools/generate_notices.py --write",
            file=sys.stderr,
        )
        return 1

    print("NOTICE and THIRD_PARTY_LICENSES.md match the third-party lock files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
