#!/usr/bin/env python3
"""Generate NOTICE and THIRD_PARTY_LICENSES.md from the dependency manifests.

Hand-maintained notice files rot. They keep listing a dependency after it is removed, and
they miss one after it is added — and both failures are invisible until someone audits the
release, which is exactly when it is most expensive to discover. Before this program,
`NOTICE` still credited `ml-sharp`, a snapshot that contributed nothing to the build.

So notices are generated, and CI runs this in ``--check`` mode and fails on drift.

Two distinct outputs, because they answer two different questions:

``NOTICE``
    What is *compiled into the artifact you downloaded*. This is the file whose accuracy is
    a licence obligation. It lists only dependencies that are actually linked into the core.

``THIRD_PARTY_LICENSES.md``
    Everything third-party the *repository* touches, including external tools that Melkor
    merely invokes and does not redistribute. It is documentation, not an obligation.

Keeping these separate matters. Listing an external AGPL trainer in `NOTICE` would imply
Melkor ships it. It does not: the adapter invokes a program the user installed themselves.

Usage::

    python3 tools/generate_notices.py --write
    python3 tools/generate_notices.py --check    # CI
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LOCK_PATH = REPO_ROOT / "third_party" / "manifest.lock.json"
ADAPTERS_DOC = "docs/adapters/index.md"

NOTICE_PATH = REPO_ROOT / "NOTICE"
THIRD_PARTY_PATH = REPO_ROOT / "THIRD_PARTY_LICENSES.md"

GENERATED_BANNER = (
    "This file is generated by tools/generate_notices.py from\n"
    "third_party/manifest.lock.json. Do not edit it by hand; edit the manifest and\n"
    "regenerate. CI fails if this file drifts from the manifest."
)


def load_lock() -> dict:
    return json.loads(LOCK_PATH.read_text(encoding="utf-8"))


def iter_shipped(lock: dict):
    """Dependencies whose code is compiled into Melkor's own artifacts.

    Yields ``(id, license, upstream, revision, license_file, note)``. Embedded
    sub-dependencies (a library bundled inside another library, like nlohmann/json inside
    tinygltf) ship too, and are yielded separately: the parent's licence does not cover
    them, and a notice that omits them is incomplete.
    """
    for dep in lock["dependencies"]:
        yield {
            "id": dep["id"],
            "license": dep["license"],
            "upstream": dep["upstream"],
            "revision": dep["revision"],
            "release": dep.get("release"),
            "license_file": dep.get("license_file"),
            "purpose": dep.get("purpose", ""),
            "patches": dep.get("patches", []),
        }
        for embedded in dep.get("embeds", []):
            yield {
                "id": embedded["id"],
                "license": embedded["license"],
                "upstream": embedded["upstream"],
                "revision": None,
                "release": embedded.get("version"),
                "license_file": embedded.get("license_file"),
                "purpose": embedded.get("purpose", ""),
                "patches": [],
                "embedded_in": dep["id"],
            }


def render_notice(lock: dict) -> str:
    lines: list[str] = []
    lines.append("Melkor")
    lines.append("Copyright (c) Sepehr Mahmoudian")
    lines.append("")
    lines.append("Licensed under the MIT License. See LICENSE.")
    lines.append("")
    for line in GENERATED_BANNER.splitlines():
        lines.append(line)
    lines.append("")
    lines.append("=" * 78)
    lines.append("")
    lines.append("Third-party code compiled into Melkor artifacts")
    lines.append("")
    lines.append(
        "The components below are redistributed as part of Melkor's binaries and source\n"
        "bundle. Their licences apply to the code they cover, not to Melkor as a whole."
    )
    lines.append("")

    for dep in iter_shipped(lock):
        lines.append("-" * 78)
        lines.append("")
        header = dep["id"]
        if dep.get("embedded_in"):
            header += f"  (embedded in {dep['embedded_in']})"
        lines.append(header)
        lines.append("")
        if dep["purpose"]:
            lines.append(f"  Purpose:  {dep['purpose']}")
        lines.append(f"  License:  {dep['license']}")
        lines.append(f"  Upstream: {dep['upstream']}")
        if dep["release"]:
            lines.append(f"  Version:  {dep['release']}")
        if dep["revision"]:
            lines.append(f"  Revision: {dep['revision']}")
        if dep["license_file"]:
            lines.append(f"  License text: {dep['license_file']}")
        if dep["patches"]:
            lines.append("")
            lines.append(
                f"  Modified by Melkor. {len(dep['patches'])} local "
                f"patch{'es' if len(dep['patches']) != 1 else ''} "
                f"under third_party/patches/{dep['id']}/:"
            )
            for patch in dep["patches"]:
                lines.append(f"    - {patch['file']}")
        lines.append("")

    lines.append("=" * 78)
    lines.append("")
    lines.append("External tools invoked but NOT redistributed")
    lines.append("")
    lines.append(
        "Melkor's reconstruction and training adapters run external programs that the user\n"
        "installs separately. Melkor does not ship their source or their model weights, and\n"
        "their licences are not Melkor's licence. Those terms — including copyleft,\n"
        "research-only, and non-commercial restrictions — are recorded per adapter."
    )
    lines.append("")
    lines.append(f"See {ADAPTERS_DOC}.")
    lines.append("")
    return "\n".join(lines)


def render_third_party(lock: dict) -> str:
    lines: list[str] = []
    lines.append("# Third-party licences")
    lines.append("")
    lines.append("<!--")
    for line in GENERATED_BANNER.splitlines():
        lines.append(line)
    lines.append("-->")
    lines.append("")
    lines.append(
        "Melkor's core is MIT-licensed. This file records every third-party component the\n"
        "repository depends on, and distinguishes what Melkor **redistributes** from what it\n"
        "merely **invokes**. That distinction is the whole point: shipping a library means its\n"
        "licence travels with our artifact, whereas calling a program the user installed does\n"
        "not."
    )
    lines.append("")
    lines.append("## Compiled into Melkor artifacts")
    lines.append("")
    lines.append(
        "These are redistributed in Melkor's binaries and source bundle. Exact upstream\n"
        "revisions are pinned in `third_party/manifest.lock.json` and verified in CI by\n"
        "`tools/verify_third_party.py`."
    )
    lines.append("")
    lines.append("| Component | Licence | Version | Upstream |")
    lines.append("|---|---|---|---|")
    for dep in iter_shipped(lock):
        name = dep["id"]
        if dep.get("embedded_in"):
            name = f"{name} <sub>(in {dep['embedded_in']})</sub>"
        version = dep["release"] or (dep["revision"][:12] if dep["revision"] else "—")
        lines.append(
            f"| {name} | {dep['license']} | {version} | [{dep['upstream'].removeprefix('https://github.com/')}]({dep['upstream']}) |"
        )
    lines.append("")

    for dep in iter_shipped(lock):
        if not dep["patches"]:
            continue
        lines.append(f"### Modifications to {dep['id']}")
        lines.append("")
        lines.append(
            f"Melkor carries local patches against upstream `{dep['revision'][:12]}`. They are\n"
            f"kept as reviewable files under `third_party/patches/{dep['id']}/` rather than\n"
            f"edited into the vendored source, so that the fork is visible and upstream can be\n"
            f"upgraded deliberately."
        )
        lines.append("")
        for patch in dep["patches"]:
            # A patch with no rationale is a policy failure (verify_third_party.py rejects it),
            # but generating notices must not crash with an unhandled KeyError on the way to
            # reporting that. Degrade to a visible placeholder instead.
            rationale = patch.get("rationale") or "(no rationale recorded — see the lock)"
            lines.append(f"- **`{patch['file']}`** — {rationale}")
            lines.append(f"  Upstream status: {patch.get('upstream_status', 'unknown')}.")
        lines.append("")

    lines.append("## Invoked but not redistributed")
    lines.append("")
    lines.append(
        "Reconstruction, training, and depth systems are separate programs. Melkor describes\n"
        "them with pinned adapter manifests; it does not vendor their source or their weights.\n"
        "Their code licences and their **model-weight licences are different fields**, because\n"
        "they routinely differ — permissive code frequently ships with research-only weights."
    )
    lines.append("")
    lines.append(
        f"The upstream projects, their licences, and why the research snapshots were removed\n"
        f"from this repository are documented in [{ADAPTERS_DOC}]({ADAPTERS_DOC})."
    )
    lines.append("")
    lines.append("## Viewer dependencies")
    lines.append("")
    lines.append(
        "The web viewer's npm dependencies and the Tauri desktop shell's Rust crates are\n"
        "locked in `viewer/package-lock.json` and `viewer/src-tauri/Cargo.lock`. The desktop\n"
        "shell generates its own crate licence inventory\n"
        "(`viewer/RUST_THIRD_PARTY_LICENSES.html`) via `cargo-about`, and `cargo-deny`\n"
        "enforces the licence policy in CI."
    )
    lines.append("")
    return "\n".join(lines)


def compare(path: Path, expected: str) -> list[str]:
    actual = path.read_text(encoding="utf-8") if path.is_file() else ""
    if actual == expected:
        return []
    diff = difflib.unified_diff(
        actual.splitlines(keepends=True),
        expected.splitlines(keepends=True),
        fromfile=f"{path.name} (committed)",
        tofile=f"{path.name} (generated)",
        n=1,
    )
    return list(diff)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="regenerate the notice files")
    mode.add_argument("--check", action="store_true", help="fail if the committed files drift")
    args = parser.parse_args()

    lock = load_lock()
    outputs = {
        NOTICE_PATH: render_notice(lock),
        THIRD_PARTY_PATH: render_third_party(lock),
    }

    if args.write:
        for path, content in outputs.items():
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO_ROOT)}")
        return 0

    failed = False
    for path, content in outputs.items():
        diff = compare(path, content)
        if diff:
            failed = True
            print(
                f"{path.relative_to(REPO_ROOT)} does not match the dependency manifest:",
                file=sys.stderr,
            )
            sys.stderr.writelines(diff)
            print(file=sys.stderr)

    if failed:
        print(
            "Notice files are stale. Run:\n"
            "    python3 tools/generate_notices.py --write",
            file=sys.stderr,
        )
        return 1

    print("NOTICE and THIRD_PARTY_LICENSES.md match third_party/manifest.lock.json.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
